# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=30)),
                ('contactUserId', models.IntegerField(null=True)),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField()),
                ('wasteId', models.IntegerField()),
                ('isPatented', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellingCompanyId', models.IntegerField()),
                ('buyingCompanyId', models.IntegerField()),
                ('wasteId', models.IntegerField()),
                ('cost', models.FloatField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.CharField(max_length=30)),
                ('companyId', models.IntegerField(null=True)),
                ('status', models.CharField(blank=True, choices=[('C', 'Company'), ('E', 'Entrepreneur'), ('O', 'Organization')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('estPrice', models.FloatField(max_length=15)),
                ('recyclingScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WastePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField()),
                ('wasteId', models.IntegerField()),
                ('price', models.FloatField(max_length=15)),
                ('minQuantity', models.FloatField(null=True)),
            ],
        ),
    ]
