# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectivezero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bestCompanyId', models.IntegerField()),
                ('bestTechnologyDesc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
