# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectivezero', '0002_auto_20180304_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bestCompanyId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bestTechnologyDesc',
            field=models.TextField(null=True),
        ),
    ]
