# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectivezero', '0003_auto_20180304_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='wasteName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
